// Timed lyric lines for /music_and_me.mp3 (seconds).
export const LYRICS = [
  { start: 0.50, end: 4.80, text: "Ok is the hardest, I swear to God" },
  { start: 4.90, end: 7.40, text: "We gon' be okay" },
  { start: 9.10, end: 12.90, text: "I'm like, \"Where you at? Can't see you, I need you now\"" },
  { start: 13.00, end: 15.00, text: "You do it so right, dare to teach me how" },
  { start: 15.10, end: 18.30, text: "You talk about a feelin', I feel it now" },
  { start: 18.42, end: 20.80, text: "Look back if I could, but I'm not allowed" },
  { start: 20.98, end: 23.60, text: "I'm like, \"Where you at? Really need you now\"" },
  { start: 23.72, end: 26.20, text: "You do it so right, dare to teach me how" },
  { start: 26.34, end: 28.60, text: "You talk about a feelin', I feel it now" },
  { start: 28.74, end: 30.80, text: "Look back if I could, but I'm not allowed" },
  { start: 30.92, end: 33.70, text: "I'm crazy and I'm nervous and I'm sweatin' and I'm blushin'" },
  { start: 33.88, end: 36.50, text: "Think I'm doin' it for somethin', but I'm doin' it for nothin'" },
  { start: 36.62, end: 38.20, text: "The look on her face, tears runnin'" },
  { start: 38.36, end: 41.10, text: "Don't know what to say, but you still say somethin'" },
  { start: 41.28, end: 43.80, text: "Feel alive when you do what you're not allowed" },
  { start: 43.92, end: 46.80, text: "But you should know, this isn't what life 'bout" },
  { start: 46.92, end: 49.00, text: "I'ma die before I ever cry out" },
  { start: 49.18, end: 51.50, text: "And I'ma get struck down if I'm a liar" },
  { start: 51.62, end: 54.00, text: "Hot headed, leaf burnt, playin' with fire" },
  { start: 54.20, end: 56.20, text: "Would you ever trade your life for desire?" },
  { start: 56.36, end: 58.80, text: "Would you ever trade your life for desire?" },
  { start: 58.96, end: 59.50, text: "Would you ever—, uh" },
  { start: 59.66, end: 62.00, text: "Would you ever—, uh" },
  { start: 71.88, end: 75.00, text: "I'm like, \"Where you at? Can't see you, I need you now\"" },
  { start: 75.24, end: 77.70, text: "You do it so right, dare to teach me how" },
  { start: 77.84, end: 80.30, text: "You talk about a feelin', I feel it now" },
  { start: 80.46, end: 82.70, text: "Look back if I could, but I'm not allowed" },
  { start: 82.80, end: 85.40, text: "I'm like, \"Where you at? Really need you now\"" },
  { start: 85.58, end: 87.90, text: "You do it so right, dare to teach me how" },
  { start: 88.08, end: 90.40, text: "You talk about a feelin', I feel it now" },
  { start: 90.58, end: 93.10, text: "Look back if I could, but I'm not allowed" },
  { start: 93.28, end: 95.70, text: "I'm crazy and I'm nervous and I'm sweatin' and I'm blushin'" },
  { start: 95.88, end: 98.30, text: "Think I'm doin' it for somethin', but I'm doin' it for nothin'" },
  { start: 98.48, end: 100.00, text: "The look on her face, tears runnin'" },
  { start: 100.20, end: 103.00, text: "Don't know what to say, but you still say somethin'" },
  { start: 103.14, end: 105.60, text: "Feel alive when you do what you're not allowed" },
  { start: 105.74, end: 108.50, text: "But you should know, this isn't what life 'bout" },
  { start: 108.60, end: 111.00, text: "I'ma die before I ever cry out" },
  { start: 111.18, end: 113.30, text: "And I'ma get struck down if I'm a liar" },
  { start: 113.48, end: 116.20, text: "Hot headed, leaf burnt, playin' with fire" },
  { start: 116.32, end: 118.80, text: "Would you ever trade your life for desire?" },
  { start: 118.92, end: 122.50, text: "Would you ever trade your life for desire?" },
  { start: 122.60, end: 123.50, text: "Would you ever—, uh" },
  { start: 123.60, end: 127.00, text: "Would you ever—, uh" }
];
