import { useEffect, useMemo, useState } from 'react';

const API_ROOT = 'https://api.blockcypher.com/v1/ltc/main/txs/';

const short = (value = '', left = 12, right = 10) =>
  value.length > left + right ? `${value.slice(0, left)}...${value.slice(-right)}` : value;

const formatLtc = (satoshis = 0) => `${(Number(satoshis) / 100_000_000).toFixed(8)} LTC`;

export default function TransactionPage({ txid }) {
  const [tx, setTx] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    let active = true;
    setTx(null);
    setError('');
    fetch(`${API_ROOT}${encodeURIComponent(txid)}`)
      .then((response) => {
        if (!response.ok) throw new Error('Transaction not found');
        return response.json();
      })
      .then((data) => active && setTx(data))
      .catch(() => active && setError('We could not find that Litecoin transaction.'));
    return () => { active = false; };
  }, [txid]);

  const totals = useMemo(() => {
    if (!tx) return { input: 0, output: 0 };
    return {
      input: (tx.inputs || []).reduce((sum, item) => sum + (item.output_value || 0), 0),
      output: (tx.outputs || []).reduce((sum, item) => sum + (item.value || 0), 0),
    };
  }, [tx]);

  return (
    <main className="tx-page">
      <div className="tx-noise" aria-hidden="true" />
      <header className="tx-header">
        <a className="tx-brand" href="/" aria-label="Back to ASARII home"><span className="tx-mark">A</span><span>ASARII<span className="tx-brand-muted"> / TX</span></span></a>
        <span className="tx-network"><i /> LITECOIN MAINNET</span>
      </header>
      <section className="tx-shell">
        <div className="tx-kicker"><span /> TRANSACTION RECEIPT</div>
        <h1>Transfer <em>verified.</em></h1>
        <p className="tx-intro">A public, read-only record of a Litecoin transaction.</p>
        <div className="tx-card">
          <div className="tx-card-top"><div><span className="tx-label">TXID</span><code>{short(txid, 18, 16)}</code></div><span className={`tx-status ${error ? 'is-error' : tx ? 'is-confirmed' : 'is-loading'}`}><i /> {error ? 'NOT FOUND' : tx ? 'CONFIRMED' : 'FETCHING'}</span></div>
          {error ? <div className="tx-error"><strong>Couldn&apos;t load receipt.</strong><span>{error}</span><a href="/">Return to asarii.xyz</a></div> : tx ? <>
            <div className="tx-hero"><div><span className="tx-label">TOTAL OUTPUT</span><strong>{formatLtc(totals.output)}</strong><span className="tx-usd">Network fee {formatLtc(tx.fees || 0)}</span></div><div className="tx-block"><span className="tx-label">BLOCK</span><strong>{tx.block_height > 0 ? tx.block_height.toLocaleString() : 'Mempool'}</strong><span className="tx-usd">{tx.confirmations || 0} confirmations</span></div></div>
            <div className="tx-grid"><div><span className="tx-label">FROM</span><code>{short(tx.inputs?.[0]?.addresses?.[0] || 'Unknown', 15, 10)}</code></div><div><span className="tx-label">TO</span><code>{short(tx.outputs?.[0]?.addresses?.[0] || 'Unknown', 15, 10)}</code></div><div><span className="tx-label">SIZE</span><span>{tx.size ? `${tx.size} bytes` : '—'}</span></div><div><span className="tx-label">SEEN</span><span>{tx.received ? new Date(tx.received).toLocaleString() : '—'}</span></div></div>
            <div className="tx-flow"><div className="tx-flow-head"><span>INPUTS <b>{tx.inputs?.length || 0}</b></span><span>OUTPUTS <b>{tx.outputs?.length || 0}</b></span></div><div className="tx-flow-track"><span className="tx-flow-in" style={{ width: `${Math.max(22, totals.input ? (totals.output / totals.input) * 100 : 22)}%` }} /><span className="tx-flow-out" /></div><div className="tx-flow-values"><span>{formatLtc(totals.input)}</span><span>{formatLtc(totals.output)}</span></div></div>
            <div className="tx-actions"><button onClick={() => navigator.clipboard?.writeText(window.location.href)}>Copy receipt link</button><a href={`https://live.blockcypher.com/ltc/tx/${txid}`} target="_blank" rel="noreferrer">Open explorer ↗</a></div>
          </> : <div className="tx-loading"><span /><span /><span /></div>}
        </div>
        <p className="tx-foot">Generated by ASARII · Data provided by BlockCypher · No keys, no custody.</p>
      </section>
    </main>
  );
}
